<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Import shared components -->
  <xacro:include filename="$(find robot_sim)/urdf/shared.xacro" />

  <!-- ros_control plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/robot</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

  <!-- Constants for robot dimensions -->
  <xacro:property name="link_radius" value="0.05" />
  <xacro:property name="link_gap" value="0.1" />
  <xacro:property name="link1_length" value="0.5" />
  <xacro:property name="link2_length" value="0.5" />
  <xacro:property name="link3_length" value="0.4" />
  <xacro:property name="joint1_low" value="0.0" />
  <xacro:property name="joint1_high" value="${PI/2}" />
  <xacro:property name="joint2_low" value="0.0" />
  <xacro:property name="joint2_high" value="${PI/2}" />
  <xacro:property name="joint3_low" value="0.0" />
  <xacro:property name="joint3_high" value="${PI/2}" />
  <xacro:property name="joint_effort_lim" value="2000" />
  <xacro:property name="joint_velocity_lim" value="15" />
  
  <!-- Enable self-collision -->
  <gazebo>
    <self_collide>true</self_collide>
  </gazebo>
  
  <!-- World link -->
  <link name="world"/>

  <!-- Table -->
  <joint name="joint_table" type="fixed">
    <parent link="world"/>
    <child link="table"/>
    <origin xyz="0 0 0.5" rpy="0 0 0"/>
  </joint>

  <link name="table">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="1 1 1" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="1 1 1" />
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="table">
    <material>Gazebo/White</material>
  </gazebo>

  <!-- Joint 0 -->
  <joint name="joint0" type="continuous">
    <parent link="table"/>
    <child link="link0"/>
    <origin xyz="0 0 0.55" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <transmission name="tran0">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint0">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor0">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Link 0 -->
  <link name="link0">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="0.5 0.5 0.1" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="0.5 0.5 0.1" />
      </geometry>
      <material name="grey"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1.0"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="link0">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- Joint 1 -->
  <joint name="joint1" type="revolute">
    <parent link="link0" />
    <child link="link1" />
    <origin xyz="0 0 ${0.1 + link_gap/2}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="${joint1_low}" upper="${joint1_high}" effort="${joint_effort_lim}" velocity="${joint_velocity_lim}"/>
    <dynamics damping="0.5" />
  </joint>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Link 1 -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${link_gap/2 + link1_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link1_length}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${link_gap/2 + link1_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link1_length}" />
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${link_gap/2 + link1_length/2}" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="link1">
    <material>Gazebo/Orange</material>
  </gazebo>
  
  <gazebo reference="link1">
    <sensor name="link1_contact_sensor" type="contact">
      <always_on>true</always_on>
      <update_rate>${sensor_update_rate}</update_rate>
      <visualize>false</visualize>
      <contact>
        <collision>link1_collision</collision>
      </contact>
      <plugin name="gazebo_ros_bumper_controller" filename="libgazebo_ros_bumper.so">
        <bumperTopicName>/link1_bumper</bumperTopicName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Joint 2 -->
  <joint name="joint2" type="revolute">
    <parent link="link1" />
    <child link="link2" />
    <origin xyz="0 0 ${link1_length + link_gap}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="${joint2_low}" upper="${joint2_high}" effort="${joint_effort_lim}" velocity="${joint_velocity_lim}"/>
    <dynamics damping="0.5" />
  </joint>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Link 2 -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${link_gap/2 + link2_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link2_length}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${link_gap/2 + link2_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link2_length}" />
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${link_gap/2 + link2_length/2}" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="link2">
    <material>Gazebo/Orange</material>
  </gazebo>
  
  <gazebo reference="link2">
    <sensor name="link2_contact_sensor" type="contact">
      <always_on>true</always_on>
      <update_rate>${sensor_update_rate}</update_rate>
      <visualize>false</visualize>
      <contact>
        <collision>link2_collision</collision>
      </contact>
      <plugin name="gazebo_ros_bumper_controller" filename="libgazebo_ros_bumper.so">
        <bumperTopicName>/link2_bumper</bumperTopicName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Joint 3 -->
  <joint name="joint3" type="revolute">
    <parent link="link2" />
    <child link="link3" />
    <origin xyz="0 0 ${link2_length + link_gap}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="${joint3_low}" upper="${joint3_high}" effort="${joint_effort_lim}" velocity="${joint_velocity_lim}"/>
    <dynamics damping="0.5" />
  </joint>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Link 3 -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${link_gap/2 + link3_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link3_length}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${link_gap/2 + link3_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link3_length}" />
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${link_gap/2 + link3_length/2}" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="link3">
    <material>Gazebo/Orange</material>
  </gazebo>
  
  <gazebo reference="link3">
    <sensor name="link3_contact_sensor" type="contact">
      <always_on>true</always_on>
      <update_rate>${sensor_update_rate}</update_rate>
      <visualize>false</visualize>
      <contact>
        <collision>link3_collision</collision>
      </contact>
      <plugin name="gazebo_ros_bumper_controller" filename="libgazebo_ros_bumper.so">
        <bumperTopicName>/link3_bumper</bumperTopicName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Joint 4 -->
  <joint name="joint4" type="continuous">
    <parent link="link3" />
    <child link="effector" />
    <origin xyz="0 0 ${link3_length + link_gap}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <dynamics damping="0.5" />
  </joint>

  <!-- Effector -->
  <link name="effector">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <sphere radius="${marker_point_radius}" />
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="effector">
    <material>Gazebo/Blue</material>
  </gazebo>

</robot>
