<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Import shared components -->
  <xacro:include filename="$(find robot_sim)/urdf/shared.xacro" />

  <!-- ros_control plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/robot</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

  <!-- Constants for robot dimensions -->
  <xacro:property name="link_radius" value="0.04" />

  <xacro:property name="offset_x" value="0" />
  <xacro:property name="offset_y" value="0" />
  <xacro:property name="offset_z" value="0.2" />

  <xacro:property name="link0_length" value="0.1215" />
  <xacro:property name="link1_length" value="0.408" />
  <xacro:property name="link2_length" value="0.376" />
  <xacro:property name="link3_length" value="0.1025" />
  <xacro:property name="link4_length" value="0.094" />
  <xacro:property name="effector_length" value="0.05" />

  <xacro:property name="link1_d" value="-0.1405" />
  <xacro:property name="link2_d" value="0.1215" />
  <xacro:property name="link3_d" value="-0.1025" />

  <xacro:property name="joint0_low" value="-0.000006" />
  <xacro:property name="joint0_high" value="3.053448" />
  <xacro:property name="joint1_low" value="-1.571984" />
  <xacro:property name="joint1_high" value="1.571984" />
  <xacro:property name="joint2_low" value="-1.529065" />
  <xacro:property name="joint2_high" value="1.571069" />
  <xacro:property name="joint3_low" value="-0.785398" />
  <xacro:property name="joint3_high" value="0.785398" />
  <xacro:property name="joint4_low" value="-3.053450" />
  <xacro:property name="joint4_high" value="3.053439" />
  
  <xacro:property name="joint_effort_lim" value="2000" />
  <xacro:property name="joint_velocity_lim" value="15" />
  
  <!-- Enable self-collision -->
  <gazebo>
    <self_collide>false</self_collide>
  </gazebo>
  
  <!-- World link -->
  <link name="world"/>

  <!-- Joint 0 -->
  <joint name="joint0" type="revolute">
    <parent link="world"/>
    <child link="link0"/>
    <origin xyz="${offset_x} ${offset_y} ${offset_z}" rpy="0 0 ${-pi/2}"/>
    <axis xyz="0 0 1"/>
    <limit lower="${joint0_low}" upper="${joint0_high}" effort="${joint_effort_lim}" velocity="${joint_velocity_lim}"/>
    <dynamics damping="0.7"/>
  </joint>

  <transmission name="tran0">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint0">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor0">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Link 0 -->
  <link name="link0">
    <collision>
      <origin xyz="0 0 ${link0_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link0_length}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${link0_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link0_length}" />
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${link0_length/2}" rpy="0 0 0" />
      <mass value="1.0"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="link0">
    <material>Gazebo/Orange</material>
  </gazebo>

  <!-- Joint 1 -->
  <joint name="joint1" type="revolute">
    <parent link="link0" />
    <child link="link1" />
    <origin xyz="0 ${link1_d} ${link0_length}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="${joint1_low}" upper="${joint1_high}" effort="${joint_effort_lim}" velocity="${joint_velocity_lim}"/>
    <dynamics damping="0.5" />
  </joint>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Link 1 -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link1_length}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link1_length}" />
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="link1">
    <material>Gazebo/Orange</material>
  </gazebo>
  
  <gazebo reference="link1">
    <sensor name="link1_contact_sensor" type="contact">
      <always_on>true</always_on>
      <update_rate>${sensor_update_rate}</update_rate>
      <visualize>false</visualize>
      <contact>
        <collision>link1_collision</collision>
      </contact>
      <plugin name="gazebo_ros_bumper_controller" filename="libgazebo_ros_bumper.so">
        <bumperTopicName>/link1_bumper</bumperTopicName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Joint 2 -->
  <joint name="joint2" type="revolute">
    <parent link="link1" />
    <child link="link2" />
    <origin xyz="0 ${link2_d} ${link1_length}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="${joint2_low}" upper="${joint2_high}" effort="${joint_effort_lim}" velocity="${joint_velocity_lim}"/>
    <dynamics damping="0.5" />
  </joint>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Link 2 -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link2_length}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link2_length}" />
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="link2">
    <material>Gazebo/Orange</material>
  </gazebo>
  
  <gazebo reference="link2">
    <sensor name="link2_contact_sensor" type="contact">
      <always_on>true</always_on>
      <update_rate>${sensor_update_rate}</update_rate>
      <visualize>false</visualize>
      <contact>
        <collision>link2_collision</collision>
      </contact>
      <plugin name="gazebo_ros_bumper_controller" filename="libgazebo_ros_bumper.so">
        <bumperTopicName>/link2_bumper</bumperTopicName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Joint 3 -->
  <joint name="joint3" type="revolute">
    <parent link="link2" />
    <child link="link3" />
    <origin xyz="0 ${link3_d} ${link2_length}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="${joint3_low}" upper="${joint3_high}" effort="${joint_effort_lim}" velocity="${joint_velocity_lim}"/>
    <dynamics damping="0.5" />
  </joint>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Link 3 -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link3_length}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link3_length}" />
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="link3">
    <material>Gazebo/Orange</material>
  </gazebo>
  
  <gazebo reference="link3">
    <sensor name="link3_contact_sensor" type="contact">
      <always_on>true</always_on>
      <update_rate>${sensor_update_rate}</update_rate>
      <visualize>false</visualize>
      <contact>
        <collision>link3_collision</collision>
      </contact>
      <plugin name="gazebo_ros_bumper_controller" filename="libgazebo_ros_bumper.so">
        <bumperTopicName>/link3_bumper</bumperTopicName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Joint 4 -->
  <joint name="joint4" type="revolute">
    <parent link="link3" />
    <child link="link4" />
    <origin xyz="0 0 ${link3_length}" rpy="${PI/2} 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="${joint4_low}" upper="${joint4_high}" effort="${joint_effort_lim}" velocity="${joint_velocity_lim}"/>
    <dynamics damping="0.5" />
  </joint>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Link 4 -->
  <link name="link4">
    <collision>
      <origin xyz="0 0 ${link4_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link4_length}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${link4_length/2}" rpy="0 0 0"/>
      <geometry>
	      <cylinder radius="${link_radius}" length="${link4_length}" />
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${link4_length/2}" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <gazebo reference="link4">
    <material>Gazebo/Orange</material>
  </gazebo>
  
  <gazebo reference="link4">
    <sensor name="link4_contact_sensor" type="contact">
      <always_on>true</always_on>
      <update_rate>${sensor_update_rate}</update_rate>
      <visualize>false</visualize>
      <contact>
        <collision>link4_collision</collision>
      </contact>
      <plugin name="gazebo_ros_bumper_controller" filename="libgazebo_ros_bumper.so">
        <bumperTopicName>/link4_bumper</bumperTopicName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Joint 5 -->
  <joint name="joint5" type="continuous">
    <parent link="link4" />
    <child link="effector" />
    <origin xyz="0 0 ${link4_length + effector_length}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <dynamics damping="0.5" />
  </joint>

  <!-- Effector -->
  <link name="effector">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
	      <sphere radius="${marker_point_radius}" />
      </geometry>
      <material name="blue" />
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.1" />
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0" />
    </inertial>
  </link>

  <gazebo reference="effector">
    <material>Gazebo/Blue</material>
  </gazebo>

</robot>
