robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  # Position Controllers ---------------------------------------
  joint0_position_controller:
    type: position_controllers/JointPositionController
    joint: joint0
    pid: {p: 1000, i: 5, d: 20}

  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 1000, i: 5, d: 20}

  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 1000, i: 5, d: 20}

  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint3
    pid: {p: 1000, i: 5, d: 20}
